### PR TITLE
Thanks for the article

### PR DESCRIPTION
**Pull request by mcguirepr89**
Hello!

I just wanted to say thank you for the article -- I've put a link to it on my repo's ReadMe.

I wanted to invite you to pull in the latest updates for your users -- I imagine they will want to "update" when they see new features (like support for 70+ notification services that were added a few days ago).

Please accept my best regards and reiterated thanks for your kind words about the project . Thank you, too, for creating the (great) build guide!! Your 3D printed housing is an awesome and cheeky touch!!

Patrick

### CODE REVIEW

**Comment by CoreProduction** [comment]
Hi @mcguirepr89 - we love what you've done with this project! When I first got started with Bird-NET a year ago it was much less accessible. Baking everything into a one-liner is just perfect.

Thanks for opening the PR - we forked the project so we may guarantee a working build for folks following the tutorial. The installer script was modified to checkout a particular commit since at the time of writing we had an install issue on the `main` branch. Are commits on the main branch stable now?

**Comment by mcguirepr89** [comment]
Hahaha always is a strong word! But there certainly have been a lot of great changes since then, and we do address bugs quickly. There are some rather substantial changes that will be pulled into the `main` branch soon, some of which you can preview from [my installation](https://virginia.birdnetpi.com). I had the privilege of corresponding with one of your followers for whom I've just recently registered a new [BirdNET-Pi subdomain](https://berowra.birdnetpi.com/) -- though he has changed his upstream to https://github.com/mcguirepr89/BirdNET-Pi.git just to get the latest updates which include some improvements in efficiency, lots of aesthetic upgrades, better retention of the best recordings (high confidence scores keep files on disk even when they become old enough for the system to cycle for disk space), and the aforementioned addition of the [Apprise Notification Suite](https://github.com/caronc/apprise).

It's definitely a VERY dynamic project, so it is a little nutty that there have been 178 commits, 2 active development branches, and 1 open PR that will be great for the way updates are handled going forward all since you forked!

I just wanted to reach out and offer my support in helping keep this fork (first of all) stable and (secondly) up to date.

If you have a chance to test the new branch out and decide if you want to pull in the latest changes:
```
git remote set-url origin https://github.com/mcguirepr89/BirdNET-Pi.git
git checkout -f main
git pull
update_birdnet.sh && update_birdnet.sh
```
You gotta double-down on the last update from your current version to do away with the old method of forcing the "Privacy Mode" which is no longer a binary On/Off but is an adjustable threshold.

Anywho, thank you so much for your wonderful article and the really great video. I've never had an acknowledgement like that, so it was pretty cool to watch!

I also noticed that you mentioned issues installing on the Raspberry Pi 0W2, but perhaps you've had more luck since? This is [my 0W2 installation](https://pi0w2.birdnetpi.com)

My very best regards!
Patrick McGuire

**Comment by CoreProduction** [comment]
> It's definitely a VERY dynamic project [...]
It's amazing to see how it's progressing - have you considered flagging specific commits as release / pre-release versions, or keeping a release branch with commits that are known to be working? For now, we'll leave our version of the new-installer.sh pointing to a cherry-picked commit that we've been able to install easily. 
Perhaps once the project is under less rapid development we can retire our fork and redirect the link to a release/stable branch.

**Comment by mcguirepr89** [comment]
I haven't figured out the best why to handle versioning -- I discussed this today with @CaiusX -- I think we'll be trying to organize development around a dedicated `development` branch. This will be the new place where folks will submit their PRs. From that branch, we'll be doing the testing and merging/reconciling the various active development branches, then we'll be pulling those into `main` at regular intervals (once a week, once every two weeks, depending on the number of new commits we accumulate, I suppose).

I should probably do more research about versioning and see about tagging specific commits as releases. Seems straight-forward enough? HA! We'll see!

**Pull request merged**
